// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (
    user_id,
    name,
    token
) VALUES (
    $1, 
    $2, 
    $3
)
RETURNING id, user_id, name, token, notification_enabled, notification_disabled_at, created_at
`

type CreateEndpointParams struct {
	UserID uuid.UUID
	Name   string
	Token  string
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.UserID, arg.Name, arg.Token)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Token,
		&i.NotificationEnabled,
		&i.NotificationDisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpointByToken = `-- name: DeleteEndpointByToken :exec
DELETE FROM endpoints
WHERE token = $1
  AND user_id = $2
`

type DeleteEndpointByTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeleteEndpointByToken(ctx context.Context, arg DeleteEndpointByTokenParams) error {
	_, err := q.db.Exec(ctx, deleteEndpointByToken, arg.Token, arg.UserID)
	return err
}

const findEndpointByToken = `-- name: FindEndpointByToken :one
SELECT id, user_id, name, token, notification_enabled, notification_disabled_at, created_at FROM endpoints
WHERE token = $1
`

func (q *Queries) FindEndpointByToken(ctx context.Context, token string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, findEndpointByToken, token)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Token,
		&i.NotificationEnabled,
		&i.NotificationDisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const findEndpointByUserID = `-- name: FindEndpointByUserID :many
SELECT id, user_id, name, token, notification_enabled, notification_disabled_at, created_at FROM endpoints
WHERE user_id = $1
`

func (q *Queries) FindEndpointByUserID(ctx context.Context, userID uuid.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, findEndpointByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Token,
			&i.NotificationEnabled,
			&i.NotificationDisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
