// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type Endpoint struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	Name                   string
	Token                  string
	NotificationEnabled    bool
	NotificationDisabledAt *time.Time
	CreatedAt              time.Time
}

type PushToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	P256dhKey string
	AuthKey   string
	Endpoint  string
	IsActive  bool
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
