// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const findUserById = `-- name: FindUserById :one
SELECT id, email, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email, updated_at)
VALUES ($1, now())
ON CONFLICT (email) 
DO UPDATE SET 
    updated_at = EXCLUDED.updated_at
RETURNING id, email, created_at, updated_at
`

func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
